name: DevSecOps
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null

jobs:
  truffle:
       name: trufflehog-actions-scan
       runs-on: ubuntu-latest
       steps:
       - name: secretsscan
         uses: actions/checkout@master
       - uses: edplato/trufflehog-actions-scan@master
         with:
          scanArguments: "--regex --entropy=false --max_depth=0 --rules /regexes.json" # Add custom options here*
  

