name: DevSecOps
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null

jobs:
  truffle:
       name: trufflehog-actions-scan
       runs-on: ubuntu-latest
       steps:
       - name: secretsscan
         uses: actions/checkout@master
       - uses: edplato/trufflehog-actions-scan@master
  

